### PR TITLE
Create Technica

### PR DESCRIPTION
**Pull request by danadoucette**
Women and Non-Binary hackathon

### CODE REVIEW

**Comment by vasa-develop** [comment]
@danadoucette Can we build any stuff using Blockchain or Web3.0 in general in this hackathon?

**Comment by danadoucette** [comment]
@vasa-develop  I don't believe there are any restrictions on what can be built. You must identify as a woman, or non-binary to enter; that is the only requirement I see.

**Comment by vasa-develop** [comment]
@danadoucette You're is right, but if I add hackathons/meetups using this approach then the list that we are creating will lose its utility. 
We are looking for hackathons/meetups which are specifically focussed on Building on Web3.0.

**Comment by danadoucette** [comment]
@vasa-develop well Web3.0 is the current standard, therefore I would imagine it would be Web3.0 builds!

**Pull request merged**
