### PR TITLE
Create nh.js

### PR DESCRIPTION
**Pull request by thisLinda**

### CODE REVIEW

**Comment by vasa-develop** [comment]
@thisLinda Thanks for your contribution.

But, this seems like a Javascript-based meetup.
Instead, we are looking for meetups in Web3.0/Blockchain Space. **You can search for "Web3.0 meetups" or "Blockchain meetups"**.

**Comment by thisLinda** [comment]
🤦

**Comment by thisLinda** [comment]
What is meant by "Last Application DateTime?"

**Comment by thisLinda** [comment]
NM. I figured it out.

**Pull request closed without merging**
